# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeUpgradeCheck < Formula
  desc "Find what breaks before you upgrade Kubernetes"
  homepage "https://github.com/runtimez-com/kube-upgrade-check"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runtimez-com/kube-upgrade-check/releases/download/v0.1.0/kube-upgrade-check_0.1.0_darwin_amd64.tar.gz"
      sha256 "e32d7b0330e5a14d50828aed8ad37bda506f4c93af0866ef452de9b8dcc3f576"

      def install
        bin.install "kube-upgrade-check"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runtimez-com/kube-upgrade-check/releases/download/v0.1.0/kube-upgrade-check_0.1.0_darwin_arm64.tar.gz"
      sha256 "dacfac14fdd0f7369dd3bef5d06eb3d737f77bad02c7f25a638caa2783505fa2"

      def install
        bin.install "kube-upgrade-check"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/runtimez-com/kube-upgrade-check/releases/download/v0.1.0/kube-upgrade-check_0.1.0_linux_amd64.tar.gz"
        sha256 "08ab867175f697c0d2a46b971aa534dfae72b0b4aa71f74299e7e18966c07ab2"

        def install
          bin.install "kube-upgrade-check"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/runtimez-com/kube-upgrade-check/releases/download/v0.1.0/kube-upgrade-check_0.1.0_linux_arm64.tar.gz"
        sha256 "9f85d41abfc9e4f39c54091f486ff22ff517f3fe526b17244de6d5cfb7b1bbad"

        def install
          bin.install "kube-upgrade-check"
        end
      end
    end
  end

  test do
    system "#{bin}/kube-upgrade-check", "version"
  end
end
