# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rtz < Formula
  desc "Operate and troubleshoot Kubernetes from the runtimez control plane"
  homepage "https://github.com/runtimez-com/runtimez-cli"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runtimez-com/runtimez-cli/releases/download/v0.1.2/rtz_0.1.2_darwin_amd64.tar.gz"
      sha256 "5745aed350c77fa611c3a73063f06c8720ac1eafd370f1d6ebba27ecbc039680"

      def install
        bin.install "rtz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runtimez-com/runtimez-cli/releases/download/v0.1.2/rtz_0.1.2_darwin_arm64.tar.gz"
      sha256 "a09c55d4d9d83411a96cd849f56959d06b49a9edb5b82db1eefa20aaf71b8ff4"

      def install
        bin.install "rtz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/runtimez-com/runtimez-cli/releases/download/v0.1.2/rtz_0.1.2_linux_amd64.tar.gz"
        sha256 "b7e3bd4a31f612eda6cfd2e13feff9fd684af119730171292b0ed9f09bfdd69e"

        def install
          bin.install "rtz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/runtimez-com/runtimez-cli/releases/download/v0.1.2/rtz_0.1.2_linux_arm64.tar.gz"
        sha256 "9a884bd334d8a355c0625f5b5aa87abb477c57b84184405f247e53ec870a79e5"

        def install
          bin.install "rtz"
        end
      end
    end
  end

  test do
    system "#{bin}/rtz", "version"
  end
end
